# Version of the Icarus theme that is currently used
version: 2.3.0
# Path or URL to the website's icon
favicon: /favicon.ico
# Path or URL to RSS atom.xml
rss: 
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo: /images/logo.png
# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
    # Facebook App ID
    fb_app_id: 
    # Facebook Admin ID
    fb_admins: 
    # Twitter ID
    twitter_id: 
    # Twitter site
    twitter_site: 
    # Google+ profile link
    google_plus: 
# Navigation bar link settings
navbar:
    # Navigation bar menu links
    menu:
        ğŸ  é¦–é¡µ: /
        ğŸ¯ å½’æ¡£: /archives
        ğŸ“š åˆ†ç±»: /categories
        ğŸ“Œ å‹é“¾: /friends
        ğŸ“ å…³äº: /about
    # Navigation bar links to be shown on the right
    #links:
        #Download on GitHub:
            #icon: fab fa-github
            #url: 'http://github.com/ppoffice/hexo-theme-icarus'
# Footer section link settings
footer:
    # Links to be shown on the right of the footer section
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'http://github.com/ppoffice/hexo-theme-icarus'
# Article display settings
article:
    # Code highlight theme
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    highlight: atom-one-light
    # Whether to show article thumbnail images
    thumbnail: false
    # Whether to show estimate article reading time
    readtime: false
# Search plugin settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Search-Plugins
search:
    # Name of the search plugin
    type: insight
# Comment plugin settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Comment-Plugins
comment:
    # Name of the comment plugin
    #type: valine
    #app_id: NP0STJ6LGAR2xXISdzVO247j-gzGzoHsz      
    # (required) LeanCloud application id
    #app_key: uK2dvHuQEPbwPghQJVPJwjVv       
    # (required) LeanCloud application key
    #notify: false          
    # (optional) receive email notification
    #verify: false          
    # (optional) show verification code
    #placeholder: æ¥ä¸€å‘è¯„è®º  à¸…Ê•â€¢Í¡Ì«â€¢Ê”à¸…   
    # (optional) comment box placeholder text
    
    type: disqus
    shortname: vensing-com

# Donation entries
# http://ppoffice.github.io/hexo-theme-icarus/categories/Donation/
#donate:
#    -
        # Donation entry name
#       type: alipay
        # Qrcode image URL
#        qrcode: ''
#    -
        # Donation entry name
#        type: wechat
        # Qrcode image URL
#        qrcode: ''
#    -
        # Donation entry name
#        type: paypal
        # Paypal business ID or email address
#        business: ''
        # Currency code
#        currency_code: USD
#    -
        # Donation entry name
#        type: patreon
        # URL to the Patreon page
#        url: ''
# Share plugin settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Share-Plugins
share:
    # Share plugin name
    type: 
# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # left sidebar settings
    left:
        # Whether the left sidebar is sticky when page scrolls
        # http://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        # å›ºå®šå·¦è¾¹è¾¹æ³¨æ (é¡µé¢æ»‘åŠ¨æ—¶)
        sticky: false 
    # right sidebar settings
    right:
        # Whether the right sidebar is sticky when page scrolls
        # http://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
# Sidebar widget settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        # Widget name
        type: profile
        # Where should the widget be placed, left or right
        position: left
        # Author name to be shown in the profile widget
        author: Vexsy
        # Title of the author to be shown in the profile widget
        author_title: åŠ¨æ¼«ã€è¿½ç•ªã€ç”µè„‘è¿·ã€ä¸Šç½‘æˆç˜¾ï¼›æ‘¸é±¼å‹åšä¸»
        # Author's current location to be shown in the profile widget
        location: China
        # Path or URL to the avatar to be shown in the profile widget
        avatar: /images/avatar.jpg
        # Email address for the Gravatar to be shown in the profile widget
        gravatar: #vensing@foxmail.com
        # Whether to show avatar image rounded or square
        avatar_rounded: false
        # Path or URL for the follow button
        follow_link: '/about'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'http://github.com/vensing'
            Twitter:
                icon: fab fa-twitter
                url: 'http://twitter.com/vensing1020'
            Telegram:
                icon: fab fa-telegram
                url: 'https://t.me/vexsy'
            Email:
                icon: fas fa-envelope
                url: 'mailto:vensing@foxmail.com'

    -
        # Widget name
        type: toc
        # Where should the widget be placed, left or right
        position: left
    #-
        # Widget name
        #type: links
        # Where should the widget be placed, left or right
        #position: left
        # Links to be shown in the links widget
        #links:
            #Mintimate: 'https://www.mintimate.cn'
            #å¯’ç©¹ã®å°å±‹: 'https://www.hqsblog.cn'
            #é›¨é›¾ã®Blog: 'https://blog.seerainfog.ooo/'
            #åºŸçŒ«åšå®¢: 'https://www.maobk.cn/'
    #-
        # Widget name
        #type: category
        # Where should the widget be placed, left or right
        #position: left
    #-
        # Widget name
        #type: tagcloud
        # Where should the widget be placed, left or right
        #position: left
    #-
        # Widget name
        #type: recent_posts
        # Where should the widget be placed, left or right
        #position: left
    -
        # Widget name
        type: archive
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: tag
        # Where should the widget be placed, left or right
        position: left
        

# warning days
warning:
    days: 60
    text: 'æœ¬æ–‡æœ€åæ›´æ–°äº %d å¤©å‰ï¼ˆ%dï¼‰ï¼Œå…¶ä¸­çš„ä¿¡æ¯å¯èƒ½å·²ç»æœ‰æ‰€å‘å±•æˆ–è€…ä¸å†é€‚ç”¨äºç°é˜¶æ®µã€‚'


# Show number of visitors to each article.
# You can visit https://leancloud.cn get AppID and AppKey.
leancloud_visitors:
    app_id: NP0STJ6LGAR2xXISdzVO247j-gzGzoHsz
    #<app_id>
    app_key: uK2dvHuQEPbwPghQJVPJwjVv
    #<app_key>
    

# Other plugin settings
plugins:
    # Enable page animations
    animejs: true
    # Enable the lightGallery and Justified Gallery plugins
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated-browser: true
    # Enable the MathJax plugin
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
    mathjax: false
    # Show the back to top button on mobile devices
    back-to-top: true
    # Google Analytics plugin settings
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
    google-analytics:
        # Google Analytics tracking id
        tracking_id: UA-138325809-1
    # Baidu Analytics plugin settings
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
    baidu-analytics:
        # Baidu Analytics tracking id
        tracking_id: 
    # Hotjar user feedback plugin
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
    hotjar:
        # Hotjar site id
        site_id: 
    # Show a loading progress bar at top of the page
    progressbar: false
    # Show the copy button in the highlighted code area
    clipboard: true
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: false
# CDN provider settings
# http://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    #cdnjs: https://cdnjs.cloudflare.com/ajax/libs/Han/3.2.7/han.min.js
    # Name or URL of the webfont CDN provider
    #fontcdn: https://cdnjs.cloudflare.com/ajax/libs/Han/3.2.7/han.min.css
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    iconcdn: fontawesome